// admin/src/components/MessageBox/MessageBox.tsx
import React, { type FC } from 'react'
import { Remarkable } from 'remarkable'
import { linkify } from 'remarkable/linkify'
import clsx from 'clsx'
import { type CommonProps } from '@models/commons'
import { type Message } from '@models/Message'
import hljs from 'highlight.js'

import style from './MessageBox.module.scss'
import 'highlight.js/styles/github.css'

const markdown = new Remarkable({
  breaks: true,
  typographer: true,
  highlight: function (str, lang) {
    if (lang && hljs.getLanguage(lang)) {
      try {
        return hljs.highlight(str, { language: lang }).value
      } catch (_) {
      }
    }

    try {
      return hljs.highlightAuto(str).value
    } catch (_) {
    }

    return '' // use external default escaping
  }
}).use(linkify)
markdown.inline.ruler.enable(['sup', 'sub'])
markdown.core.ruler.enable(['abbr'])
markdown.block.ruler.enable(['footnote', 'deflist'])

/**
 * Displays a single chat message.
 * It is used to display both the user's messages and the Cheshire Cat's responses.
 */
const MessageBox: FC<MessageBoxProps> = ({ text, sender, className, ...rest }) => {
  const isBot = sender === 'bot'
  const classList = clsx(style.message, isBot ? style.bot : style.user, className)

  return (
    <article className={classList} {...rest}>
      {isBot && (<div className={style.avatar}>😺</div>)}
      <span className={style.content} dangerouslySetInnerHTML={{ __html: markdown.render(text) }} />
    </article>
  )
}

export interface MessageBoxProps extends CommonProps {
  /**
   * Message to display
   */
  text: string
  /**
   * Message sender
   */
  sender?: Message['sender']
}

export default React.memo(MessageBox)

// admin/src/components/MessageBox.vue
<script setup lang="ts">
import hljs from 'highlight.js'
import { Remarkable } from 'remarkable'
import { linkify } from 'remarkable/linkify'
import 'highlight.js/styles/github.css'

const markdown = new Remarkable({
    breaks: true,
    typographer: true,
    highlight: (str, lang) => {
        if (lang && hljs.getLanguage(lang)) {
            try { return hljs.highlight(str, { language: lang }).value } 
            catch (_) {}
        }
        try { return hljs.highlightAuto(str).value } 
        catch (_) {}
        return ''
    }
}).use(linkify)
markdown.inline.ruler.enable(['sup', 'sub'])
markdown.core.ruler.enable(['abbr'])
markdown.block.ruler.enable(['footnote', 'deflist'])

const props = defineProps<{
    sender: 'bot' | 'user',
    text: string
}>()

const cleanedText = props.text.replace(/\"(.+)\"/g, '$1')
</script>

<template>
	<div class="chat gap-y-1" :class="[sender === 'bot' ? 'chat-start' : 'chat-end']">
		<div class="chat-header px-2 font-semibold">
			{{ sender === 'bot' ? '😺 Cheshire Cat' : 'You 👤' }}
		</div>
		<div class="chat-bubble min-h-fit" v-html="markdown.render(cleanedText)" />
	</div>
</template>
